logging:
  level: debug

database:
  uri: postgres://username:password@localhost:5432/tsexpress?sslmode=disable
  queryLogging: true

redis:
  url: redis://localhost:6379
  password: password

templates:
  externalUrl: http://localhost:3000
