logging:
  level: debug

database:
  uri: postgres://username:password@localhost:5432/tsexpress?sslmode=disable
  queryLogging: true

amqp:
  uri: amqp://username:password@localhost:5672/

templates:
  externalUrl: http://localhost:3000
