kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.app.configMap }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/version: {{ .Values.app.version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.yml: |
    server:
      address: 0.0.0.0
      port: {{ .Values.app.port }}
