{{- define "secrets" }}
database:
  uri: {{ printf "postgres://%s:%s@%s.%s.svc.cluster.local:%d/%s?sslmode=disable"
    .Values.postgres.username 
    .Values.postgres.password 
    .Values.postgres.name 
    .Release.Namespace 
    (.Values.postgres.port | int) 
    .Values.postgres.dbname }}
amqp:
  uri: {{ printf "amqp://%s:%s@broker.messaging.svc.cluster.local:5672/"
    .Values.rabbitmq.username .Values.rabbitmq.password }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/Opaque
data:
  secrets.yml: {{ include "secrets" . | b64enc | quote }}
